sudo: required
services: 
  - docker

before_install:
  - docker build -t james3263/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run james3263/react-test npm test -- --coverage

after_success:
  - docker build -t james3263/multi-client ./client
  - docker build -t james3263/multi-nginx ./nginx 
  - docker build -t james3263/multi-server ./server
  - docker build -t james3263/multi-worker ./worker
  # log in docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push img to docker hub
  - docker push james3263/multi-client
  - docker push james3263/multi-nginx
  - docker push james3263/multi-server
  - docker push james3263/multi-worker